[project]
name = ""
version = "0.0.1"
dependencies = [
    "django>=4.2.0",
    "django-reversion>=5.0.0",
    "openai>=1.0.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "groq>=0.4.2",
    "wikipedia>=1.4.0",
    "perfect>=0.0.1",
]

[tool.uv]
package = false
