# Generated by Django 5.1.4 on 2024-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('see', 'See'), ('eat', 'Eat'), ('sleep', 'Sleep'), ('shop', 'Shop'), ('drink', 'Drink'), ('play', 'Play')], max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('hours', models.CharField(blank=True, max_length=500, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('city_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'rank'],
                'indexes': [models.Index(fields=['city_name', 'category'], name='cities_poin_city_na_a958f9_idx')],
            },
        ),
    ]
