# Generated by Django 5.1.4 on 2024-12-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pointofinterest',
            name='cities_poin_city_na_a958f9_idx',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='city_name',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='cities.city'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city', 'category'], name='cities_poin_city_id_22c68b_idx'),
        ),
    ]
