# Generated by Django 5.1.4 on 2024-12-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_validation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='validation',
            name='cities_vali_parent__6befe1_idx',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='parent_key',
        ),
        migrations.AddField(
            model_name='validation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='cities.city'),
        ),
        migrations.AddIndex(
            model_name='validation',
            index=models.Index(fields=['parent'], name='cities_vali_parent__5cba7f_idx'),
        ),
    ]
