# Generated by Django 5.1.4 on 2024-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_remove_validation_cities_vali_parent__6befe1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
