# Generated by Django 5.1.4 on 2025-01-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_add_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_lists', to='cities.city')),
                ('pois', models.ManyToManyField(related_name='lists', to='cities.pointofinterest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
