# Generated by Django 5.1.4 on 2025-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_add_poi_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image of this POI', max_length=500, null=True),
        ),
    ]
