# Generated by Django 5.1.4 on 2025-01-17 11:35

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_city_about_city_wikivoyage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Stored image file of this city', null=True, upload_to=cities.models.city_image_path),
        ),
    ]
