# Generated by Django 5.1.4 on 2025-01-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image_url',
        ),
    ]
