# Generated by Django 5.1.4 on 2025-01-17 12:15

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_remove_city_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Stored image file of this POI', null=True, upload_to=cities.models.poi_image_path),
        ),
    ]
