# Generated by Django 5.1.4 on 2025-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_remove_pointofinterest_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='osm_id',
            field=models.CharField(blank=True, help_text='OpenStreetMap ID for this POI', max_length=50, null=True),
        ),
    ]
