from django.urls import path
from . import views

urlpatterns = [
    path('', views.city_list, name='city_list'),
    path('cities.json', views.city_list_json, name='city_list_json'),
    path('generate/', views.generate_text_view, name='generate_text_view'),
    path('city/<str:city_name>/', views.city_detail, name='city_detail'),
    path('city/<str:city_name>/map/', views.city_map, name='city_map'),
    path('city/<str:city_name>/delete/', views.delete_city, name='delete_city'),
    path('city/<str:city_name>/dump/', views.dump_city, name='dump_city'),
    path('city/<str:city_name>/generate/', views.generate_text, name='generate_text'),
    path('city/<str:city_name>/generate-list/', views.generate_list, name='generate_list'),
    path('import-city/', views.import_city, name='import_city'),
    path('import-status/<str:task_id>/', views.check_import_status, name='check_import_status'),
    path('city/<str:city_name>/poi/<int:poi_id>/history/', views.poi_history, name='poi_history'),
    path('city/<str:city_name>/poi/<int:poi_id>/revert/<int:revision_id>/', views.poi_revert, name='poi_revert'),
    path('city/<str:city_name>/poi/<int:poi_id>/edit/', views.poi_edit, name='poi_edit'),
    path('city/<str:city_name>/poi/<int:poi_id>/', views.poi_detail, name='poi_detail'),
    path('city/<str:city_name>/poi/<int:poi_id>/delete/', views.delete_poi, name='delete_poi'),
    path('city/<str:city_name>/poi/merge/', views.poi_merge, name='poi_merge'),
    path('city/<str:city_name>/lists/', views.poi_lists, name='poi_lists'),
    path('city/<str:city_name>/lists/create/', views.create_poi_list, name='create_poi_list'),
    path('city/<str:city_name>/lists/<int:list_id>/delete/', views.delete_poi_list, name='delete_poi_list'),
    path('city/<str:city_name>/lists/<int:list_id>/append/', views.append_to_list, name='append_to_list'),
    path('city/<str:city_name>/tasks/<str:task_id>/execute/', views.execute_task, name='execute_task'),
    path('tasks/<str:task_id>/status/', views.check_task_status, name='check_task_status'),
    path('city/<str:city_name>/poi/<int:poi_id>/fetch_image/', views.fetch_poi_image, name='fetch_poi_image'),
    path('city/<str:city_name>/poi/<int:poi_id>/delete_image/', views.delete_poi_image, name='delete_poi_image'),
    path('city/<str:city_name>/poi/<int:poi_id>/save_image/', views.save_poi_image, name='save_poi_image'),
    path('city/<str:city_name>/fetch_image/', views.fetch_city_image, name='fetch_city_image'),
    path('city/<str:city_name>/save_image/', views.save_city_image, name='save_city_image'),
    path('city/<str:city_name>/delete_image/', views.delete_city_image, name='delete_city_image'),
    path('city/<str:city_name>/update_about/', views.update_about, name='update_about'),
]
